# Generated by Django 6.0.2 on 2026-02-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_status_1dbab2_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_created_b5c671_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_assigne_cb12f9_idx",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
