# Generated by Django 6.0.2 on 2026-02-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_ticket_tickets_status_1dbab2_idx_and_more"),
    ]

    operations = []
