# Generated by Django 4.2.28 on 2026-02-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = []
